name: "Format Check"
on:
  pull_request:
    paths:
    - "src/**"
    - ".github/workflows/format-check.yml"
  push:
    paths: 
    - "src/**"
    - ".github/workflows/format-check.yml"
    branches:
      - main
      - dev
      
jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: GCC Problem Matcher
      uses: ammaraskar/gcc-problem-matcher@0.3.0
    - name: Clang Format Check
      uses: jidicula/clang-format-action@v4.14.0
      with:
        clang-format-version: '18'
        check-path: 'src'